config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :crawlers, only: [:index, :create, :show], path: 'importar'
  resources :exporter, only: :show
  resources :status, path: 'status', only: :show
  resources :feedbacks, only: :create

  get "/politica-de-privacidade", to: 'privacy_policy#index'
  get "/termos-e-condicoes", to: 'terms_and_conditions#index'

  if Rails.env.production?
    require 'sidekiq/web'
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV['ADMIN_EMAIL'] && password == ENV['ADMIN_PASSWORD']
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'
  root 'crawlers#index'
end

app/controllers/crawlers_controller.rb
class CrawlersController < ApplicationController
  def index; end

  def create
    user = SkoobUser.login(params[:email], params[:password])

    if user.skoob_user_id > 0
      Publication.where(skoob_user_id: user.skoob_user_id).destroy_all

      user.update(import_status: 1)
      SkoobImporterJob.perform_later(user) unless Rails.env.test?
      send_slack_notification(user.skoob_user_id)

      redirect_to crawler_path(user.skoob_user_id)
    else
      flash[:error] = 'Não conseguimos fazer login no Skoob. Verifique seu email e senha e tente novamente.'
      redirect_to root_path
    end
  rescue Net::HTTPGatewayTimeout
    flash[:error] = 'O Skoob não está respondendo, verifique se consegue logar no site deles normalmente ou tente novamente mais tarde'
    redirect_to root_path
  end

  def show
    @user = SkoobUser.find_by(skoob_user_id: params[:id])

    if @user.import_status == 0 && Publication.where(skoob_user_id: @user.skoob_user_id).count == 0
      redirect_to root_path
    end
  end

  private

  def send_slack_notification(skoob_user_id)
    message = "User https://www.skoob.com.br/usuario/#{skoob_user_id} is importing..."
    Slack::Message.send(message)
  end
end

app/views/crawlers/_imported.html.erb
<img src="/done.svg" class="status-icon" />

app/views/crawlers/_importing.html.erb
<svg width="148px" height="148px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="uil-hourglass"><rect x="0" y="0" width="100" height="100" fill="none" class="bk"></rect><g transform="rotate(0)"><path fill="none" stroke="#007282" stroke-width="5" stroke-miterlimit="10" d="M58.4,51.7c-0.9-0.9-1.4-2-1.4-2.3s0.5-0.4,1.4-1.4 C70.8,43.8,79.8,30.5,80,15.5H70H30H20c0.2,15,9.2,28.1,21.6,32.3c0.9,0.9,1.4,1.2,1.4,1.5s-0.5,1.6-1.4,2.5 C29.2,56.1,20.2,69.5,20,85.5h10h40h10C79.8,69.5,70.8,55.9,58.4,51.7z" class="glass"></path><clipPath id="uil-hourglass-clip1"><rect x="15" y="25.8333" width="70" height="19.1667" class="clip"><animate attributeName="height" from="25" to="0" dur="1s" repeatCount="indefinite" vlaues="25;0;0" keyTimes="0;0.5;1"></animate><animate attributeName="y" from="20" to="45" dur="1s" repeatCount="indefinite" vlaues="20;45;45" keyTimes="0;0.5;1"></animate></rect></clipPath><clipPath id="uil-hourglass-clip2"><rect x="15" y="74.1667" width="70" height="5.83333" class="clip"><animate attributeName="height" from="0" to="25" dur="1s" repeatCount="indefinite" vlaues="0;25;25" keyTimes="0;0.5;1"></animate><animate attributeName="y" from="80" to="55" dur="1s" repeatCount="indefinite" vlaues="80;55;55" keyTimes="0;0.5;1"></animate></rect></clipPath><path d="M29,23c3.1,11.4,11.3,19.5,21,19.5S67.9,34.4,71,23H29z" clip-path="url(#uil-hourglass-clip1)" fill="#ffab00" class="sand"></path><path d="M71.6,78c-3-11.6-11.5-20-21.5-20s-18.5,8.4-21.5,20H71.6z" clip-path="url(#uil-hourglass-clip2)" fill="#ffab00" class="sand"></path><animateTransform attributeName="transform" type="rotate" from="0 50 50" to="180 50 50" repeatCount="indefinite" dur="1s" values="0 50 50;0 50 50;180 50 50" keyTimes="0;0.7;1"></animateTransform></g></svg>

app/views/crawlers/_importing_card.html.erb
<section class="importing-card col-sm-10">
  <% if user.import_status == 1 %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Importação</h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Status</dt>
          <dd>
            <span class="running" data-status>Em andamento</span>
          </dd>

          <dt><br />Email</dt>
          <dd>
            <%= user.email %>
          </dd>

          <dt><br />Skoob ID</dt>
          <dd>
            <%= user.skoob_user_id %>
          </dd>

          <dd data-count>
          </dd>
        </dl>

        <div class="progress">
          <div class="progress-bar progress-bar-striped bg-success progress-bar-animated"
            role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"
            style="width: 0%">
          </div>
        </div>

        <div data-duplicated class="hidden">
          <dl>
            <dt><br />
              Livros duplicados
            </dt>
            <dd>

            </dd>
          </dl>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/crawlers/_loading.html.erb
<svg width="148px" height="148px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="uil-hourglass"><rect x="0" y="0" width="100" height="100" fill="none" class="bk"></rect><g transform="rotate(0)"><path fill="none" stroke="#007282" stroke-width="5" stroke-miterlimit="10" d="M58.4,51.7c-0.9-0.9-1.4-2-1.4-2.3s0.5-0.4,1.4-1.4 C70.8,43.8,79.8,30.5,80,15.5H70H30H20c0.2,15,9.2,28.1,21.6,32.3c0.9,0.9,1.4,1.2,1.4,1.5s-0.5,1.6-1.4,2.5 C29.2,56.1,20.2,69.5,20,85.5h10h40h10C79.8,69.5,70.8,55.9,58.4,51.7z" class="glass"></path><clipPath id="uil-hourglass-clip1"><rect x="15" y="25.8333" width="70" height="19.1667" class="clip"><animate attributeName="height" from="25" to="0" dur="1s" repeatCount="indefinite" vlaues="25;0;0" keyTimes="0;0.5;1"></animate><animate attributeName="y" from="20" to="45" dur="1s" repeatCount="indefinite" vlaues="20;45;45" keyTimes="0;0.5;1"></animate></rect></clipPath><clipPath id="uil-hourglass-clip2"><rect x="15" y="74.1667" width="70" height="5.83333" class="clip"><animate attributeName="height" from="0" to="25" dur="1s" repeatCount="indefinite" vlaues="0;25;25" keyTimes="0;0.5;1"></animate><animate attributeName="y" from="80" to="55" dur="1s" repeatCount="indefinite" vlaues="80;55;55" keyTimes="0;0.5;1"></animate></rect></clipPath><path d="M29,23c3.1,11.4,11.3,19.5,21,19.5S67.9,34.4,71,23H29z" clip-path="url(#uil-hourglass-clip1)" fill="#ffab00" class="sand"></path><path d="M71.6,78c-3-11.6-11.5-20-21.5-20s-18.5,8.4-21.5,20H71.6z" clip-path="url(#uil-hourglass-clip2)" fill="#ffab00" class="sand"></path><animateTransform attributeName="transform" type="rotate" from="0 50 50" to="180 50 50" repeatCount="indefinite" dur="1s" values="0 50 50;0 50 50;180 50 50" keyTimes="0;0.7;1"></animateTransform></g></svg>

app/views/crawlers/_table_card.html.erb
<section class="results-table slide-in-fwd-center col-sm-10">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title" data-table-card-title></h3>
    </div>
    <div class="panel-body">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Título</th>
            <th scope="col">Autor(a)</th>
            <th scope="col">ISBN</th>
            <th scope="col">Editora</th>
            <th scope="col">Tipo</th>
          </tr>
        </thead>
        <tbody data-table-card-body>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/crawlers/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h2 class="page-header">Exporte seus livros do Skoob</h2>
    <p class="lead">
      Você quer migrar para o <a href="https://www.goodreads.com/">Goodreads</a>
      mas não quer recadastrar todos os seus livros, um por um, novamente?
    </p>
    <p class="lead">
      O Goodreads possui uma <a href="https://www.goodreads.com/review/import" />ferramenta de importação</a>,
      e tudo o que você precisa é exportar seus livros do skoob no formato correto.
      Nós fazemos isso para você!
    </p>
    <p class="lead">
      Basta entrar com a sua conta do Skoob e esperar o download do arquivo começar.
      E não se preocupe, não armazenamos sua senha. Você pode conferir isso no
      <a href="https://github.com/arturcp/skoob-exporter">código fonte</a> deste projeto.
    </p>
    <p class="lead">
      Se quiser falar comigo, <a href="https://twitter.com/artur_caliendo">me manda um alô no Twitter.</a>
    </p>
  </div>
  <div class="col-md-4">
    <input type="hidden" value="<% request.fullpath %>">
    <input type="hidden" value="<% request.protocol %>">
    <div class="login-box">
      <%= form_tag crawlers_path, class: 'form-signin', id: 'crawler-form' do %>
        <div class="form-group">
          <label>Email</label>
          <%= text_field_tag 'email', nil, class: 'form-control', required: true %>
        </div>

        <br />

        <div class="form-group">
          <label>Senha</label>
          <%= password_field_tag 'password', nil, class: 'form-control', required: true %>
        </div>

        <br />

        <div class="form-group">
          <% if ENV["SHOW_SKOOB_PERFORMANCE_WARNING"] == "true" %>
            <div class="alert-box">
              <strong>Atenção:</strong> Estamos tendo problemas intermitentes de comunicação com o Skoob, algumas pessoas estão conseguindo exportar, outras não. Se você não conseguir
              exportar, tente novamente mais tarde. Se o problema persistir, <a href="https://twitter.com/artur_caliendo">me avise no Twitter</a>.
            </div>
          <% end %>

          <% if ENV["SHOW_SKOOB_CAPTCHA_WARNING"] == "true" %>
            <div class="alert-box">
              <strong>Atenção:</strong> O Skoob adicionou uma verificação contra bots na página de login deles, o que faz com que nosso exportador não funcione. Estou pesquisando uma solução, mas por enquanto, não é possível exportar seus livros. Se você tiver alguma ideia, <a href="https://twitter.com/artur_caliendo">me avise no Twitter</a>.
            </div>
          <% end %>

          <% if ENV["SHOW_SKOOB_CAPTCHA_WARNING"] != "true" %>
            <%= button_tag 'Gerar', type: "submit", class: 'btn btn-lg btn-primary btn-block', id: 'crawler-submit' %>
          <% end %>
          <span class="loading-info">
            Você já será redirecionado para outra página, aguarde um momento... estamos conectando com sua conta do Skoob.
          </span>
        </div>
      <% end %>

      <% if flash[:error] %>
        <div class="alert alert-danger login-alert" role="alert">
          <%= flash[:error] %>
        </div>
        <% flash[:error] = nil %>
      <% end %>
    </div>
  </div>
</div>

app/views/crawlers/show.html.erb
<div class="row import-status" data-loading-url="<%= status_path(@user.skoob_user_id) %>">
  <div class="col-sm-2 text-center">
    <div class="imported-indicator">
      <%= render 'imported' %>
    </div>

    <div class="importing-indicator">
      <%= render 'importing' %>
    </div>
    <p>
      <%=
        submit_tag 'Recomeçar', class: 'btn btn-lg btn-primary btn-block',
          :onclick => "window.location = '#{root_path}'"
      %>
    </p>
    <div class="hidden" id="download">
      <div class="heartbeat">
        <%= link_to 'Baixar', exporter_path(@user.skoob_user_id), class: 'btn btn-lg btn-success btn-block' %>
      </div>
      <br />
      <div class="disclaimer">
        Agora você só precisa clicar em "Baixar" e usar o arquivo gerado no Goodreads!
      </div>
    </div>
  </div>

  <%= render 'importing_card', user: @user %>
  <%= render 'table_card' %>
</div>